
// DO NOT CHANGE THIS FILE //

const staff= [
  {
    title: "Miss.",
    firstName: "Geneva",
    lastName: "Collins",
    age:33,
    gender: "Male",
    language: "Turkish",
    race: "Hispanic",
    experience: 11,
    roomNumber: 488,
    phoneExt: 392,
    isActive: true,
  },
  {
    title: "Miss.",
    firstName: "Joni",
    lastName: "Cardenas",
    age:20,
    gender: "Male",
    language: "Dutch",
    race: "Hispanic",
    experience: 4,
    roomNumber: 481,
    phoneExt: 319,
    isActive: false,
  },
  {
    title: "Miss.",
    firstName: "Cote",
    lastName: "Frye",
    age:54,
    gender: "Female",
    language: "Spanish",
    race: "Afro-american",
    experience: 25,
    roomNumber: 337,
    phoneExt: 246,
    isActive: true,
  },
  {
    title: "Miss.",
    firstName: "Giles",
    lastName: "Mason",
    age:21,
    gender: "Female",
    language: "Dutch",
    race: "Afro-american",
    experience: 5,
    roomNumber: 356,
    phoneExt: 386,
    isActive: false,
  },
  {
    title: "Mrs.",
    firstName: "Shepard",
    lastName: "Hinton",
    age:44,
    gender: "Female",
    language: "Turkish",
    race: "White",
    experience: 16,
    roomNumber: 131,
    phoneExt: 302,
    isActive: true,
  },
  {
    title: "Mrs.",
    firstName: "Alisha",
    lastName: "Davenport",
    age:61,
    gender: "Female",
    language: "Dutch",
    race: "Asian",
    experience: 25,
    roomNumber: 414,
    phoneExt: 189,
    isActive: true,
  },
  {
    title: "Mr.",
    firstName: "Wood",
    lastName: "Woodward",
    age:39,
    gender: "Female",
    language: "Turkish",
    race: "Afro-american",
    experience: 16,
    roomNumber: 313,
    phoneExt: 215,
    isActive: false,
  },
  {
    title: "Mrs.",
    firstName: "Malinda",
    lastName: "Martinez",
    age:25,
    gender: "Male",
    language: "Dutch",
    race: "White",
    experience: 3,
    roomNumber: 346,
    phoneExt: 442,
    isActive: true,
  },
  {
    title: "Mr.",
    firstName: "Phoebe",
    lastName: "Jimenez",
    age:64,
    gender: "Male",
    language: "Turkish",
    race: "Black",
    experience: 28,
    roomNumber: 206,
    phoneExt: 456,
    isActive: true,
  },
  {
    title: "Mrs.",
    firstName: "Lynne",
    lastName: "James",
    age:32,
    gender: "Female",
    language: "Germany",
    race: "Latino",
    experience: 10,
    roomNumber: 373,
    phoneExt: 403,
    isActive: true,
  },
  {
    title: "Mirs.",
    firstName: "Ela",
    lastName: "Martins",
    age:28,
    gender: "Female",
    language: "Turkish",
    race: "White",
    experience: 6,
    roomNumber: 323,
    phoneExt: 231,
    isActive: true,
  }
]
